import {expect,test} from '@playwright/test';
test.use({serviceWorkers:'block'});
test('storage redesign keeps history context and configures reserve and SSH priority',async({page})=>{
 test.setTimeout(120000);
 const locations=[{id:1,name:'DATA 2',free_bytes:420e9,total_bytes:4000e9,reserve_bytes:0,enabled:true,mappings:[{arr_instance_id:1,arr_root:'/data2/SERIES',plex_root:'/media2/SERIES',plex_section_id:'2',subdirectory:''}]}];
 const active={id:8,source_id:1,destination_id:2,status:'running',desired_state:'run',params:{name:'Libérer DATA 2',transfer_mode:'rsync_ssh'},items:[{id:8,title:'Persona4 the ANIMATION',status:'copying',media_type:'series',size_bytes:21e9,progress:{copied_bytes:12e9,bytes:500e6,file_size_bytes:1e9,file:'Season 1/Persona4 S01E18.mkv',bytes_per_second:21e6,updated_at:Date.now()/1000},presentation:{remaining_counts:{episodes:8,seasons:1}},snapshot:{}}]};
 const completed={id:4,source_id:1,destination_id:2,status:'completed',desired_state:'run',released_bytes:56e9,params:{name:'Séries archivées',transfer_mode:'rsync_ssh'},items:[{id:4,title:'Série terminée',media_type:'series',status:'completed',size_bytes:56e9,snapshot:{},presentation:{counts:{episodes:25,seasons:1}},progress:{started_at:'2026-10-06T21:32:00',finished_at:'2026-10-06T22:18:00',copy_seconds:2000,measured_copy_bytes:40e9}}]};
 const connection={id:1,name:'TrueNAS',method:'ssh',trusted:true,tested:true,has_private_key:true,has_password:true,connection:{host:'192.168.1.50',port:22,user:'truenas_admin',auth:'key',auth_fallback:true}};
 const accesses=[{id:1,name:'TrueNAS',method:'ssh',connection_id:1,roots:[{arr_instance_id:1,arr_root:'/data2/SERIES',path:'/mnt/data2/SERIES'}]}];
 const requests=[];
 await page.route('**/api/**',async route=>{active.items[0].progress.updated_at=Date.now()/1000;const path=new URL(route.request().url()).pathname,method=route.request().method();if(method==='PUT'||method==='POST')requests.push({path,body:route.request().postDataJSON()});let json=path==='/api/session'?{role:'admin',is_owner:true}:path==='/api/storage/transfers'?[active,completed]:path==='/api/storage/locations'?locations:path==='/api/storage/connections'?[connection]:path==='/api/storage/accesses'?accesses:path==='/api/storage/instances'?[{id:1,name:'Sonarr',arr_type:'sonarr',enabled:true}]:path==='/api/storage/roots'?[{arr_instance_id:1,name:'Sonarr',arr_type:'sonarr',arr_roots:['/data2/SERIES'],plex_roots:[{section_id:'2',path:'/media2/SERIES',library:'Séries'}]}]:path.startsWith('/api/storage')?[]:{};if(path==='/api/storage/connections/1'&&method==='PUT')json=connection;if(path==='/api/storage/connections/1/test')json={...connection,auth_method:'password'};await route.fulfill({json});});
 await page.goto('/storage',{waitUntil:'domcontentloaded'});
 await expect(page.getByText('Persona4 the ANIMATION',{exact:true})).toBeVisible();
 await expect(page.getByText('8 épisode(s) à finir')).toBeVisible();
 await page.screenshot({path:`.codex/redesign-transfers-${test.info().project.name}.png`,fullPage:true});
 await page.getByRole('tab',{name:'Historique',exact:true}).click();
 await expect(page.getByText('20 Mo/s',{exact:true})).toBeVisible();
 await expect(page.getByText('25 épisodes · 1 saisons')).toBeVisible();
 await page.getByRole('button',{name:'Détails',exact:true}).click();
 await expect(page.getByRole('tab',{name:'Historique',exact:true})).toHaveAttribute('aria-selected','true');
 await page.getByRole('button',{name:'← Historique',exact:true}).click();
 await page.getByRole('tab',{name:'Stockages',exact:true}).click();
 await page.getByRole('button',{name:'Configurer',exact:true}).first().click();
 await page.getByText('Options avancées',{exact:true}).click();
 await page.getByLabel('Réserve d’espace libre',{exact:true}).check();
 await page.getByLabel('Unité',{exact:true}).selectOption('percent');
 await page.getByLabel('Valeur',{exact:true}).fill('5');
 await expect(page.getByText('5 % ≈ 200 Go')).toBeVisible();
 await page.getByRole('dialog').getByRole('button',{name:'Enregistrer',exact:true}).click();
 await expect.poll(()=>requests.some(r=>r.path==='/api/storage/locations/1'&&r.body.reserve_percent===5)).toBe(true);
 await page.getByRole('button',{name:'Gérer les connexions',exact:true}).click();
 await page.getByRole('button',{name:'Configurer',exact:true}).click();
 await page.getByLabel('Méthode prioritaire',{exact:true}).selectOption('password');
 await page.getByRole('button',{name:'Tester la connexion',exact:true}).click();
 await expect(page.getByText('Connexion réussie avec le mot de passe.')).toBeVisible();
 await page.screenshot({path:`.codex/redesign-connection-${test.info().project.name}.png`,fullPage:true});
 await page.getByRole('button',{name:'Enregistrer la connexion',exact:true}).click();
 await expect.poll(()=>requests.some(r=>r.path==='/api/storage/connections/1/assignments'&&r.body.roots[0]?.path==='/mnt/data2/SERIES')).toBe(true);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
