<template>
 <fieldset class="transfer-methods"><legend>Modes de transfert et priorités</legend>
  <p>Choisissez les modes autorisés, puis leur ordre. Le premier qui passe les contrôles est retenu. Aucun changement de mode après le début de la copie.</p>
  <div v-for="method in ordered" :key="method.value" class="transfer-method" :class="{selected:selected.includes(method.value),unavailable:Boolean(unavailableReason(method.value))}">
   <div class="method-heading"><label class="method-choice"><input type="checkbox" :aria-describedby="unavailableReason(method.value)?`unavailable-${method.value}`:undefined" :checked="selected.includes(method.value)" :disabled="busy || (method.value!=='arr'&&!available(method.value).length && !selected.includes(method.value))" @change="toggle(method.value)" /><strong>{{ method.label }}</strong></label><div v-if="selected.includes(method.value)" class="priority"><span>Priorité {{ selected.indexOf(method.value)+1 }}</span><UiButton :disabled="busy || selected.indexOf(method.value)===0" :aria-label="`Monter la priorité de ${method.label}`" @click="move(method.value,-1)">↑</UiButton><UiButton :disabled="busy || selected.indexOf(method.value)===selected.length-1" :aria-label="`Baisser la priorité de ${method.label}`" @click="move(method.value,1)">↓</UiButton></div></div>
   <small v-if="unavailableReason(method.value)" :id="`unavailable-${method.value}`" class="method-unavailable">{{ unavailableReason(method.value) }}</small>
   <small class="method-description">{{ method.description }}</small>
   <p v-if="method.value==='arr'" class="api-playback-warning" role="note">Attention : une lecture détectée avant le lancement reporte le titre. Si elle commence après, Arr poursuit le déplacement ; une pause ici ne peut pas arrêter sa commande.</p>
   <template v-if="selected.includes(method.value) && method.value!=='arr'"><label>Accès validé<select :value="accessId(method.value)" :disabled="busy" @change="setAccess(method.value,Number(($event.target as HTMLSelectElement).value))"><option :value="0">Choisir un accès</option><option v-for="access in available(method.value)" :key="access.id" :value="access.id">{{ access.name }}</option></select></label><small v-if="!available(method.value).length">Configurez et validez les chemins de toutes les racines choisies.</small></template>
  </div>
  <fieldset v-if="selected.some(m=>m!=='arr')" class="verification-choices"><legend>Vérification des fichiers</legend><label :class="{chosen:form.verification!=='renforce'}"><input type="radio" name="storage-verification" value="standard" :checked="form.verification!=='renforce'" :disabled="busy" @change="form.verification='standard'" /><span><strong>Standard · rsync</strong><small>Vérification intégrée au transfert, sans relecture complète supplémentaire lors d’une copie normale. Recommandé.</small></span></label><label :class="{chosen:form.verification==='renforce'}"><input type="radio" name="storage-verification" value="renforce" :checked="form.verification==='renforce'" :disabled="busy" @change="form.verification='renforce'" /><span><strong>Renforcée · SHA-256</strong><small>Relit entièrement les deux copies. Peut fortement ralentir le déplacement sur un partage NFS / SMB ou un montage réseau. En SSH, les calculs restent sur le serveur.</small></span></label></fieldset>
  <p v-else class="verification-arr">Vérification du déplacement gérée par Sonarr / Radarr.</p>
  <UiButton :disabled="busy" @click="$emit('configure')">Configurer les connexions et les chemins</UiButton>
 </fieldset>
</template>
<script setup lang="ts">
import {computed} from 'vue';
import UiButton from '@/components/ui/UiButton.vue';
const props=defineProps<{accesses:any[],busy:boolean}>();const form=defineModel<any>({required:true});
const methods=[{value:'arr',label:'API Sonarr / Radarr',description:'Arr déplace les fichiers. Une pause suspend les prochains titres ; la commande déjà lancée peut continuer.'},{value:'rsync_ssh',label:'Rsync par SSH',description:'Copie et vérification sur le serveur SSH. La source et la destination doivent partager la même connexion.'},{value:'rsync_local',label:'Rsync local',description:'Copie et vérification dans le moteur, avec les volumes montés dans Docker.'}];
const selected=computed<string[]>(()=>form.value.transfer_methods ?? [form.value.transfer_mode||'arr']);
const ordered=computed(()=>[...selected.value.map(m=>methods.find(item=>item.value===m)!).filter(Boolean),...methods.filter(m=>!selected.value.includes(m.value))]);
const available=(mode:string)=>props.accesses.filter(a=>a.method===(mode==='rsync_ssh'?'ssh':'local')&&a.validation?.revision===a.revision&&(form.value.routes||[]).every((route:any)=>[...(route.source_roots||[]),route.destination_root].filter(Boolean).every(root=>a.roots.some((r:any)=>r.arr_instance_id===route.arr_instance_id&&r.arr_root===root))));
function unavailableReason(mode:string):string{
 if(mode==='arr')return '';
 const accesses=props.accesses.filter(a=>a.method===(mode==='rsync_ssh'?'ssh':'local'));
 if(!accesses.length)return mode==='rsync_ssh'?'Indisponible : aucun accès SSH configuré pour les stockages.':'Indisponible : aucun accès aux volumes montés configuré pour les stockages.';
 if(!accesses.some(a=>a.validation?.revision===a.revision))return 'Indisponible : les chemins de cet accès doivent être testés et validés dans Stockages.';
 if(!available(mode).length)return 'Indisponible : aucun accès validé ne couvre toutes les sources et destinations sélectionnées.';
 return '';
}
const accessId=(mode:string)=>form.value.access_ids?.[mode] ?? (form.value.transfer_mode===mode?form.value.access_id:0) ?? 0;
function setAccess(mode:string,id:number){form.value.access_ids={...form.value.access_ids,[mode]:id};}
function toggle(mode:string){const next=selected.value.includes(mode)?selected.value.filter(m=>m!==mode):[...selected.value,mode];form.value.transfer_methods=next;if(mode!=='arr'&&!accessId(mode))setAccess(mode,available(mode)[0]?.id||0);}
function move(mode:string,delta:number){const next=[...selected.value],i=next.indexOf(mode);[next[i],next[i+delta]]=[next[i+delta],next[i]];form.value.transfer_methods=next;}
defineEmits<{configure:[]}>();
</script>
<style scoped lang="scss">
@use '@/styles/foundations/breakpoints' as bp;
.transfer-methods{padding:16px;border:1px solid var(--border);border-radius:12px;margin:20px 0 0;min-width:0}.transfer-methods>p{font-size:13px;margin:0 0 12px;color:var(--text-muted);line-height:1.5}.transfer-method{padding:12px;border:1px solid var(--border);border-radius:10px;margin-bottom:8px;min-width:0}.transfer-method.unavailable{background:var(--surface-2);border-color:var(--border)}.transfer-method.unavailable .method-heading,.transfer-method.unavailable .method-description{opacity:.5}.transfer-method.unavailable .method-choice{cursor:not-allowed}.method-unavailable{display:block;margin:6px 0 0 28px;font-size:13px;line-height:1.5;color:var(--text-muted)}.transfer-method.selected{border-color:var(--accent);background:var(--bg-hover)}.method-heading{display:flex;justify-content:space-between;gap:12px;align-items:center}.method-heading .method-choice{display:flex;flex-direction:row;gap:10px;align-items:center;margin:0;min-width:0;cursor:pointer}.method-choice input[type=checkbox]{width:18px!important;height:18px!important;min-height:18px!important;max-height:18px!important;min-width:18px;margin:0;padding:0!important;flex:0 0 18px;accent-color:var(--accent)}.method-choice strong{font-size:14px;font-weight:600}.priority{display:flex;gap:6px;align-items:center;flex-shrink:0}.priority span{font-size:12px;color:var(--text-muted);white-space:nowrap}.priority button{padding:4px 8px;min-height:44px;min-width:44px}.method-description{display:block;font-size:12px;line-height:1.5;color:var(--text-muted);margin:6px 0 0 28px}.transfer-methods label:not(.method-choice){display:grid;gap:6px;margin:10px 0}.transfer-methods>button{margin-top:6px}.verification-choices{margin:16px 0;padding:12px;min-width:0}.transfer-methods .verification-choices label{display:flex;flex-direction:row;align-items:flex-start;gap:12px;padding:12px;border:1px solid var(--border);border-radius:10px;min-height:44px}.verification-choices label.chosen{border-color:var(--accent)}.verification-choices input[type=radio]{flex:0 0 18px;width:18px!important;height:18px!important;min-height:18px!important;margin:3px 0 0;padding:0!important;accent-color:var(--accent)}.verification-choices span{min-width:0}.verification-choices small{display:block;margin-top:6px;font-size:13px;line-height:1.5}.verification-arr{font-size:13px;color:var(--text-muted)}.transfer-methods small{color:var(--text-muted)}.api-playback-warning{color:var(--red-text, #ef7070);font-size:13px;line-height:1.5;margin:8px 0 0 28px}@include bp.until(tablet){.method-heading{flex-wrap:wrap}.priority{margin-left:28px}.method-description{margin-left:0}}
</style>
