<template>
 <ModalShell :open="true" title="3 · Aperçu des déplacements" :busy="busy" :error="error" panel-class="storage-preview-modal" @close="$emit('close')">
  <StorageObjectiveSummary :plan="plan" :selected="selected" :gb="gb" @alternative="applyAlternative" />
  <p>Les séries sont déplacées entièrement. L’espace prévu ne sera libéré qu’après suppression sûre des originaux.</p>
  <section v-for="group in plan.groups" :key="group.body.arr_instance_id"><h3>{{ group.name }} · {{ group.body.source_roots?.join(', ') || group.body.source_root }} → {{ group.body.destination_root }}</h3>
   <p>Mode retenu : <strong>{{ methodLabel(group.transfer_mode || group.body.transfer_mode) }}</strong></p><p>Vérification : <strong>{{ verificationLabel(group) }}</strong></p><p v-if="group.note" class="preview-note">{{ group.note }}</p><p v-if="group.skipped_methods?.length" class="warning">Contrôles non validés pour {{ group.skipped_methods.map(methodLabel).join(', ') }}. Le mode suivant a été retenu avant toute copie.</p>
   <p v-for="source in group.sources || [group.source]" :key="source.id">{{ source.name }} : {{ gb(source.free_bytes) }} → {{ gb(source.free_bytes==null?null:source.free_bytes+sourceVolume(group,source.id)) }} libres après déplacement</p><p>Destination : {{ gb(group.destination.free_bytes) }} → {{ gb(group.destination.free_bytes==null?null:group.destination.free_bytes-volume(group)) }} libres</p>
   <p v-if="!group.goal_covered" class="warning">Objectif d’espace partiellement couvert.</p><p v-if="group.submitted">Lot déjà lancé.</p>
   <UiDataTable :label="`Titres proposés ${group.name}`" :rows="group.items" :columns="columns" :row-key="row=>row.key"><template #cell-select="{row}"><input v-model="selected" type="checkbox" :value="row.key" :disabled="busy || group.submitted || row.protected" :aria-label="`Sélectionner ${row.title}`" /></template><template #cell-size="{row}">{{ gb(row.size_bytes) }}</template><template #cell-source="{row}"><code>{{ row.snapshot.source_arr }}</code></template><template #cell-destination="{row}"><code>{{ row.snapshot.destination_arr }}</code></template><template #cell-protection="{row}"><UiButton variant="ghost" :disabled="busy || row.protected || group.submitted" @click="$emit('protect',row)">{{ row.protected?'Protégé':'Conserver ici' }}</UiButton></template></UiDataTable>
   <details v-if="group.excluded.length"><summary>{{ group.excluded.length }} titre(s) écartés</summary><p v-for="item in group.excluded" :key="item.key">{{ item.title }} : {{ item.explanation }} <UiButton v-if="!item.protected && group.catalogue?.some((candidate:any)=>candidate.key===item.key) && !selected.includes(item.key)" variant="ghost" :disabled="busy || group.submitted" @click="includeItem(group,item)">Ajouter à la sélection</UiButton></p></details>
  </section><label v-if="needsApproval" class="check"><input v-model="approved" type="checkbox" /> J’accepte cette sélection qui ne remplit pas exactement les objectifs demandés.</label><div class="actions"><UiButton :disabled="busy" @click="$emit('close')">Retour à la préparation</UiButton><UiButton :disabled="busy || !selected.length || (needsApproval && !approved)" @click="$emit('save')">Enregistrer la tâche</UiButton><UiButton variant="primary" :loading="busy" :disabled="!selected.length || (needsApproval && !approved)" @click="$emit('launch')">Lancer la sélection</UiButton></div>
 </ModalShell>
</template>
<script setup lang="ts">
import StorageObjectiveSummary from './StorageObjectiveSummary.vue';
import {computed,ref,watch} from 'vue';import ModalShell from '@/components/ui/ModalShell.vue';import UiDataTable,{type UiColumn} from '@/components/ui/UiDataTable.vue';import UiButton from '@/components/ui/UiButton.vue';
const props=defineProps<{plan:any,busy:boolean,error:string,gb:(v:any)=>string}>();const selected=defineModel<string[]>({required:true});
const methodLabel=(mode:string)=>({'arr':'API Sonarr / Radarr','rsync_ssh':'Rsync par SSH','rsync_local':'Rsync local'} as Record<string,string>)[mode]||mode;
const verificationLabel=(group:any)=>(group.transfer_mode || group.body.transfer_mode)==='arr'?'Déplacement géré par Sonarr / Radarr':group.body.verification==='renforce'?'Renforcée · SHA-256':'Standard · rsync';
const volume=(group:any)=>group.items.filter((i:any)=>selected.value.includes(i.key)).reduce((s:number,i:any)=>s+i.size_bytes,0);
const sourceVolume=(group:any,id:number)=>group.items.filter((i:any)=>selected.value.includes(i.key) && (i.snapshot.source_location_id===id || !i.snapshot.source_location_id)).reduce((s:number,i:any)=>s+i.size_bytes,0);
const selectedBytes=computed(()=>props.plan.groups.reduce((s:number,g:any)=>s+volume(g),0));
const approved=ref(false);
watch(()=>selected.value.join(','),()=>approved.value=false);
const needsApproval=computed(()=>{const requested=props.plan.requested_bytes ?? props.plan.groups.reduce((n:number,g:any)=>n+(g.requested_bytes||0),0);const count=props.plan.requested_titles ?? props.plan.groups.reduce((n:number,g:any)=>n+(g.requested_titles||0),0);return (props.plan.mode||props.plan.groups[0]?.body.mode)!=='selection' && ((requested>0 && (selectedBytes.value>requested*1.25 || selectedBytes.value<requested))||(count && selected.value.length!==count));});
const columns:UiColumn[]=[{key:'select',label:'Choix'},{key:'title',label:'Titre',card:'title'},{key:'size',label:'Volume'},{key:'source',label:'Source'},{key:'destination',label:'Destination'},{key:'explanation',label:'Sélection'},{key:'protection',label:'Protection',card:'actions'}];
function includeItem(group:any,item:any){const candidate=group.catalogue.find((i:any)=>i.key===item.key);if(!candidate || candidate.protected)return;if(!group.items.some((i:any)=>i.key===item.key))group.items.push(candidate);selected.value=[...selected.value,item.key];}
function applyAlternative(keys:string[]){for(const group of props.plan.groups){for(const item of group.catalogue||[]){if(keys.includes(item.key) && !group.items.some((i:any)=>i.key===item.key))group.items.push(item);}}selected.value=[...keys];}
defineEmits<{close:[],launch:[],save:[],protect:[item:any]}>();
</script>
<style>.storage-preview-modal{width:min(1100px,calc(100vw - 32px));color:var(--text)}.storage-preview-modal .actions{display:flex;gap:12px;flex-wrap:wrap}.storage-preview-modal .check{min-height:44px;display:flex;align-items:center;gap:10px}.storage-preview-modal code{overflow-wrap:anywhere;white-space:normal}.preview-note{color:var(--muted);font-size:var(--fs-sm)}</style>
