<template>
 <section class="job-list">
  <AppSubnav v-model:active="filter" :items="filterItems" variant="tabs" class="compact-subnav" aria-label="Filtrer les tâches" />
  <p v-if="!filteredJobs.length">Aucune tâche dans cette section.</p>
  <article v-for="job in filteredJobs" :key="job.id" class="storage-card transfer-batch">
   <div class="task-main"><h2>{{ job.params?.name || `Tâche #${job.id}` }}</h2><strong class="task-status">{{ status(job.status) }}</strong><div class="task-primary"><UiButton v-if="job.status==='draft'" variant="primary" :disabled="busy" @click="$emit('verify',job)">Vérifier et lancer</UiButton><UiButton v-else-if="job.status!=='completed'" :disabled="busy" @click="$emit('command',job.id,job.desired_state==='run' && ['running','queued'].includes(job.status)?'pause':'resume')">{{ job.desired_state==='run' && ['running','queued'].includes(job.status)?'Pause':'Reprendre le lot' }}</UiButton><details class="task-menu"><summary :aria-label="`Autres actions de la tâche ${job.id}`">⋯</summary><div class="task-menu-content"><UiButton v-if="job.status==='draft'" :disabled="busy" @click="$emit('edit',job)">Modifier</UiButton><UiButton v-if="job.status==='draft'" :disabled="busy" @click="removing=job">Supprimer le brouillon</UiButton><UiButton v-if="job.items.some((i:any)=>['blocked','failed'].includes(i.status)) && job.status!=='draft'" :disabled="busy || job.status==='running'" @click="$emit('command',job.id,'retry')">Réessayer les titres en erreur</UiButton><UiButton v-if="!['draft','completed'].includes(job.status)" :disabled="busy || job.desired_state==='stop'" @click="$emit('command',job.id,'stop')">Arrêter les prochains titres</UiButton><UiButton :disabled="busy" @click="$emit('duplicate',job)">Créer une nouvelle tâche similaire</UiButton></div></details></div></div>
   <div class="task-subline"><span class="task-route">{{ instanceName(job) }} · {{ job.params?.source_roots?.join(', ') || locationName(job.source_id) }} → {{ job.params?.destination_root || locationName(job.destination_id) }}</span><span>{{ job.items.length }} titres · {{ gb(job.planned_bytes) }}</span></div>
   <div v-if="job.status!=='draft'" class="batch-summary"><span>{{ finished(job) }} / {{ job.items.length }} terminés</span><span>{{ job.items.length-finished(job) }} restants</span><span>{{ gb(job.released_bytes) }} libérés</span></div>
   <p v-if="activeItem(job)">Maintenant : <strong>{{ activeItem(job).title }}</strong> · {{ status(activeItem(job).status) }}</p><p v-else-if="job.status!=='draft'">{{ job.status==='completed'?'Lot terminé':'En attente du prochain titre' }}</p>
   <p v-if="job.status!=='draft' && job.desired_state !== 'run'">{{ job.desired_state==='pause'?'Pause':'Arrêt' }} demandé : {{ job.params?.transfer_mode==='arr'?'les prochains titres sont suspendus ; une copie Arr déjà lancée peut continuer.':'les fichiers partiels restent conservés.' }}</p>

   <progress v-if="job.status!=='draft' && job.items.length" :value="finished(job)" :max="job.items.length" :aria-label="`Titres terminés de la tâche ${job.id}`" />
   <p v-if="activeItem(job) && ['arr_pending','copying'].includes(activeItem(job).status) && job.params?.transfer_mode==='arr'">Déplacement en cours dans {{ job.items.some((i:any)=>i.media_type==='series')?'Sonarr':'Radarr' }}. La progression de copie n’est pas fournie ; le suivi compte les titres terminés.</p>
   <div v-if="issues(job).length" class="task-issues"><strong>{{ issues(job).length }} titre(s) à traiter</strong><ul><li v-for="issue in reasons(job)" :key="issue.reason">{{ issue.count }} titre(s) : {{ issue.reason }}<small>{{ advice(issue.reason) }}</small></li></ul><p>Consultez les détails des titres pour corriger le motif, puis réessayez. Les autres titres peuvent continuer.</p></div>
   <details class="task-titles"><summary>Voir les {{ job.items.length }} titres et leurs détails</summary>
   <UiDataTable v-if="items(job).length" :label="`Titres du lot ${job.id}`" :rows="items(job)" :columns="columns" :row-key="row=>row.id">
    <template #cell-size="{row}">{{ gb(row.size_bytes) }}</template>
    <template #cell-state="{row}">{{ status(row.status) }}<small v-if="job.params?.transfer_mode!=='arr' && row.status==='copying'">{{ copyPercent(row) }} % · {{ rateLabel(row) }}</small></template>
    <template #cell-updated="{row}">{{ date(row.updated_at) }}</template>
    <template #cell-details="{row}"><details><summary>{{ row.reason?'Voir le motif':'Chemins et activité' }}</summary><p v-if="row.reason" class="warning">{{ row.reason }}</p><p>Original : {{ row.snapshot?.source_arr }}</p><p>Destination : {{ row.snapshot?.destination_arr }}</p><p v-if="row.progress?.file">Fichier : {{ row.progress.file }}</p></details></template>
   </UiDataTable><p v-else>Aucun titre ne correspond à ce filtre dans ce lot.</p>
   <details class="task-metadata"><summary>Objectifs et dates</summary><p v-if="job.status==='draft'">Tâche enregistrée, aucun transfert lancé</p><p>{{ job.params?.mode==='minimum_free'?'Espace libre minimum':'Espace à libérer' }} : {{ gb((job.params?.goal_gb||0)*1e9) }} par racine</p><p v-for="(value,root) in job.params?.root_goals || {}" :key="root">{{ root }} : {{ gb(Number(value)*1e9) }}</p><p>Dernière activité : {{ date(job.updated_at) }}</p><p>Créé : {{ date(job.created_at) }} · Début : {{ date(jobStart(job)) }} · Fin : {{ date(jobEnd(job)) }} · Durée : {{ elapsed(job) }}</p></details>
   </details>
  </article>
  <ModalShell :open="Boolean(removing)" title="Supprimer le brouillon ?" :busy="busy" @close="removing=null"><p>Cette tâche et sa sélection seront supprimées. Aucun fichier média ne sera déplacé ou supprimé.</p><div class="actions"><UiButton @click="removing=null">Annuler</UiButton><UiButton :disabled="busy" @click="$emit('remove',removing.id);removing=null">Supprimer le brouillon</UiButton></div></ModalShell>
 </section>
</template>
<script setup lang="ts">
import AppSubnav from '@/components/ui/AppSubnav.vue';
import ModalShell from '@/components/ui/ModalShell.vue';
import {computed,ref,toRef} from 'vue';import UiButton from '@/components/ui/UiButton.vue';import UiDataTable,{type UiColumn} from '@/components/ui/UiDataTable.vue';import {useStorageTelemetry} from './useStorageTelemetry';
const props=defineProps<{jobs:any[],locations:any[],busy:boolean,tab:string,instances?:any[]}>();const tab=toRef(props,'tab');
const {visibleJobs,gb,date,locationName,status,activeItem,copyPercent,rateLabel,jobStart,jobEnd,elapsed}=useStorageTelemetry(toRef(props,'locations'),toRef(props,'jobs'),tab,ref(null),ref<string[]>([]));
const instanceName=(job:any)=>props.instances?.find(i=>i.id===job.params?.arr_instance_id)?.name||`Instance ${job.params?.arr_instance_id || 'non précisée'}`;
function advice(reason:string){if(/lecture|playing/i.test(reason))return 'Attendre la fin de la lecture, puis reprendre.';if(/espace|capacity|insuffisant/i.test(reason))return 'Libérer de la place à destination avant de réessayer.';if(/connexion|accès|accessible/i.test(reason))return 'Vérifier les services et leurs accès avant de réessayer.';return 'Vérifier le motif et les chemins dans les détails avant de réessayer.';}
const filters=[{key:'all',label:'Toutes'},{key:'draft',label:'À lancer'},{key:'active',label:'En cours'},{key:'issues',label:'En pause / À traiter'},{key:'completed',label:'Terminées'}];const filter=ref('all'),removing=ref<any>(null);
const filterItems=computed(()=>filters.map(choice=>({...choice,count:countJobs(choice.key)})));
const issues=(job:any)=>job.items.filter((i:any)=>['blocked','failed','deferred','plex_pending'].includes(i.status));
function reasons(job:any){const counts=new Map<string,number>();for(const item of issues(job)){const reason=item.reason||status(item.status);counts.set(reason,(counts.get(reason)||0)+1);}return [...counts].map(([reason,count])=>({reason,count}));}
function matchesJob(job:any,key:string){return key==='all'||(key==='draft'?job.status==='draft':key==='active'?['running','queued'].includes(job.status):key==='completed'?job.status==='completed':['paused','stopped','blocked','failed'].includes(job.status)||issues(job).length>0);}
const taskPool=computed(()=>props.tab==='history'?props.jobs.filter(j=>['completed','blocked','stopped','paused','failed'].includes(j.status)):props.jobs);
const filteredJobs=computed(()=>taskPool.value.filter(j=>matchesJob(j,filter.value)));
const countJobs=(key:string)=>taskPool.value.filter(j=>matchesJob(j,key)).length;
const items=(job:any)=>filter.value==='issues'?issues(job):job.items;const finished=(job:any)=>job.items.filter((i:any)=>i.status==='completed').length;
const columns:UiColumn[]=[{key:'title',label:'Titre',card:'title'},{key:'size',label:'Volume'},{key:'state',label:'Étape / état'},{key:'updated',label:'Dernière activité'},{key:'details',label:'Détails'}];
defineEmits<{command:[id:number,action:string],create:[],edit:[job:any],duplicate:[job:any],verify:[job:any],remove:[id:number]}>();
</script>

<style scoped>.task-route{overflow-wrap:anywhere}.transfer-batch progress{width:100%;height:8px;accent-color:var(--accent)}.task-titles{margin:20px 0}.task-issues{border-left:3px solid var(--accent);padding:8px 16px;margin:16px 0}.transfer-batch .actions{display:flex;flex-wrap:wrap;gap:10px}.transfer-batch header{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap}</style>

<style scoped lang="scss">
@use '@/styles/foundations/breakpoints' as bp;
.compact-subnav :deep(.app-subnav__scroller){justify-content:center}.transfer-batch{padding:14px 18px}.task-main{display:flex;align-items:center;gap:14px}.task-main h2{font-size:1rem;margin:0;min-width:0;overflow-wrap:anywhere}.task-status{font-size:.8rem;margin-left:auto}.task-primary{display:flex;align-items:center;gap:8px}.task-subline{display:flex;gap:16px;justify-content:space-between;color:var(--text-muted);font-size:.85rem;margin-top:6px}.task-subline>span:last-child{white-space:nowrap}.task-menu{position:relative}.task-menu summary{cursor:pointer;padding:6px 12px;list-style:none;font-size:1.2rem}.task-menu-content{position:absolute;right:0;top:100%;z-index:5;background:var(--bg-card,var(--bg));border:1px solid var(--border);border-radius:10px;padding:8px;display:grid;gap:6px;min-width:230px;box-shadow:0 8px 25px #0004}.task-titles,.task-metadata{margin:8px 0 0;font-size:.85rem}.transfer-batch .batch-summary{margin:8px 0;font-size:.85rem}.task-issues{font-size:.85rem}.job-list>button{justify-self:end;width:auto}@include bp.until(phablet){.task-main{flex-wrap:wrap;gap:8px}.task-primary{margin-left:auto}.task-subline{flex-direction:column;gap:4px}.compact-subnav :deep(.app-subnav__scroller){justify-content:flex-start}}
</style>

<style scoped>.task-toolbar{display:flex;justify-content:flex-end}.storage-card.transfer-batch{padding:12px 16px;margin-bottom:0}.storage-card.transfer-batch .task-titles{padding:0;margin:6px 0 0}.storage-card.transfer-batch .task-titles>summary{min-height:28px;padding:0}.storage-card.transfer-batch .task-menu{padding:0}.storage-card.transfer-batch .task-menu>summary{min-height:32px}.storage-card.transfer-batch .batch-summary{padding:4px 0}.storage-card.transfer-batch .task-main h2{line-height:1.3}.storage-card.transfer-batch .task-subline{margin-top:4px}</style>
