// Libellés lisibles des champs validés par settingsSchema.ts. Volontairement séparé du
// schéma : ce fichier est importé statiquement, le schéma (et Zod) restent différés.
export const settingsFieldLabels: Record<string, string> = {
  plex_url: 'URL Plex',
  tautulli_url: 'URL Tautulli',
  tracearr_url: 'URL Tracearr',
  seer_url: 'URL Seer',
  public_base_url: 'URL publique',
  ntfy_url: 'URL ntfy',
  gotify_url: 'URL Gotify',
  gdpr_contact_email: 'E-mail de contact RGPD',
  smtp_from: 'Expéditeur SMTP',
  admin_notification_email: 'E-mail des notifications admin',
  tmdb_region: 'Région TMDB',
  seer_mode: 'Mode Seer',
  series_notify_granularity: 'Granularité des notifications séries',
  watchlist_source_priority: 'Source prioritaire de la watchlist',
  availability_confirmation_mode: 'Confirmation de disponibilité',
  poll_interval_seconds: 'Intervalle de synchronisation',
  arr_poll_interval_seconds: 'Intervalle *arr',
  arr_queue_interval_seconds: 'Intervalle de la file *arr',
  torrent_status_interval_seconds: 'Intervalle des torrents',
  activity_retention_days: "Rétention de l'historique",
  digest_hour: 'Heure du résumé',
  digest_minute: 'Minute du résumé',
  notification_purge_hour: 'Heure de purge des notifications',
  vf_upgrade_min_confidence: 'Confiance minimale VF',
  vf_upgrade_search_concurrency: 'Recherches VF simultanées',
  vf_upgrade_max_searches_per_run: 'Recherches VF par passage',
  torrent_min_size_gb: 'Taille minimale des torrents',
  torrent_max_size_gb: 'Taille maximale des torrents',
  torrent_ratio_limit: 'Limite de ratio',
  torrent_seed_time_limit_hours: 'Durée de seed maximale',
};
