<template>
  <AppPage title="Stockage et transferts">
    <UiFeedback v-if="error" type="error" :message="error" />
    <nav class="storage-tabs" aria-label="Sections du stockage">
      <UiButton v-for="section in tabs" :key="section.key" :variant="tab === section.key ? 'primary' : 'secondary'" @click="tab = section.key">{{ section.label }}</UiButton>
    </nav>

    <section v-if="tab === 'overview'" class="storage-grid">
      <article class="storage-card summary-card"><h2>Titres restants</h2><strong class="metric">{{ remainingItems.length }}</strong><p>{{ gb(remainingBytes) }} à déplacer dans les tâches enregistrées</p><small>{{ activeJobs.length }} tâche(s) en cours ou en attente · {{ pausedJobs.length }} en pause ou arrêtée(s)</small><div class="card-footer"><UiButton @click="tab = 'transfers'">Voir les transferts</UiButton></div></article>
      <article class="storage-card summary-card"><h2>Espace libéré</h2><strong class="metric">{{ gb(releasedBytes) }}</strong><p>{{ completedItems.length }} titre(s) terminés</p><small>Seuls les originaux supprimés après validation sont comptabilisés.</small><div class="card-footer"><UiButton @click="tab = 'history'">Voir l’historique</UiButton></div></article>
      <article class="storage-card summary-card"><h2>Configuration</h2><strong class="metric">{{ locations.length }} stockage(s)</strong><p>{{ mappingRows.length }} correspondance(s) enregistrée(s) sur {{ rootRows.filter(r => r.arr_root).length }} racine(s) détectée(s)</p><small>{{ locations.filter(l => l.enabled && l.health === 'ok').length }} stockage(s) actif(s) avec montage vérifié. Un montage vérifié ne valide pas à lui seul le contenu Arr/Plex.</small><div class="card-footer"><UiButton @click="tab = 'settings'">Configurer les stockages</UiButton></div></article>
      <article v-if="!locations.length" class="storage-card wide"><h2>Commencer par les correspondances</h2><p>Associez les racines Sonarr/Radarr aux dossiers Plex, puis renseignez le montage du moteur. Les capacités seront affichées après son contrôle.</p><UiButton @click="tab = 'settings'">Associer</UiButton></article>
      <article class="storage-card wide"><h2>Capacité des stockages</h2><p v-if="!locations.length">Les capacités seront disponibles après l’enregistrement des stockages et le contrôle de leurs montages.</p><div class="capacity-grid"><article v-for="location in locations" :key="location.id" class="capacity-card"><h3>{{ location.name }}</h3><strong class="metric">{{ gb(location.free_bytes) }} libres</strong><template v-if="location.total_bytes != null && location.free_bytes != null"><div class="capacity-track" role="meter" :aria-label="`Espace occupé sur ${location.name}`" :aria-valuenow="usedPercent(location)" aria-valuemin="0" aria-valuemax="100"><span class="capacity-used" :style="{width: usedPercent(location) + '%'}"></span><span class="capacity-reserve" :style="{width: reservePercent(location) + '%'}"></span></div><p>{{ gb(Math.max(0,location.total_bytes-location.free_bytes)) }} occupés / {{ gb(location.total_bytes) }}</p></template><p v-else>Capacité non mesurée</p><p>Réserve : {{ gb(location.reserve_bytes) }} · disponible après réserve : {{ gb(location.free_bytes == null ? null : Math.max(0,location.free_bytes-location.reserve_bytes)) }}</p><p>Libre après les tâches prévues : <strong>{{ gb(projectedFree(location)) }}</strong></p><small>Projection indicative, incluant les tâches en pause et les titres à traiter. D’autres écritures peuvent modifier l’espace libre.</small><p>{{ remainingFor(location.id).length }} titre(s) en sortie · {{ gb(remainingFor(location.id).reduce((total:number,item:any)=>total+item.size_bytes,0)) }}</p><p :class="location.health === 'ok' ? 'healthy' : 'warning'">{{ location.health === 'ok' ? 'Montage vérifié' : 'Montage indisponible ou non vérifié' }} · {{ location.enabled ? 'Actif' : 'Désactivé' }}</p><small>{{ location.mount_path }} · contrôle : {{ date(location.checked_at) }}</small></article></div></article>
      <article class="storage-card wide"><h2>Transfert actif</h2><p v-if="!activeJobs.length">Aucun transfert actif.</p><div v-for="job in activeJobs" :key="job.id" class="active-transfer"><header><strong>{{ locationName(job.source_id) }} → {{ locationName(job.destination_id) }}</strong><span>{{ status(job.status) }}</span></header><template v-if="activeItem(job)"><h3>{{ activeItem(job).title }}</h3><p>{{ status(activeItem(job).status) }} · {{ gb(activeItem(job).size_bytes) }}</p><progress :value="copyPercent(activeItem(job))" max="100" :aria-label="`Progression de copie de ${activeItem(job).title}`"></progress><p>Copie : {{ copyPercent(activeItem(job)) }} % · {{ rateLabel(activeItem(job)) }}</p><small v-if="activeItem(job).progress?.file">{{ activeItem(job).progress.file }}</small><p>Copie restante du lot : {{ copyEta(job) }}</p><p>Vérification et confirmation Plex : durée restante non estimée.</p><small>Le débit doit être récent et mesuré sur une phase de copie. L’estimation ne comprend pas la vérification ni la bascule Arr/Plex.</small></template><p v-else>En attente du prochain titre.</p><p>{{ job.items.filter((i:any)=>i.status==='completed').length }} / {{ job.items.length }} titre(s) terminés · {{ gb(job.released_bytes) }} libérés</p><p v-if="job.desired_state!=='run'">{{ job.desired_state==='pause'?'Pause':'Arrêt' }} demandé.</p><div class="actions"><UiButton :disabled="busy || job.desired_state==='pause'" @click="command(job.id,'pause')">Pause</UiButton><UiButton :disabled="busy || (job.status==='running' && job.desired_state==='run')" @click="command(job.id,'resume')">Reprendre</UiButton><UiButton @click="tab='transfers'">Voir le détail</UiButton></div></div></article>
      <article v-if="remainingRows.length" class="storage-card wide"><h2>À déplacer par stockage et type</h2><p>Volumes des titres non terminés dans les tâches enregistrées, y compris ceux en pause ou à traiter. Ce tableau ne représente pas l’ensemble du catalogue.</p><UiDataTable label="Titres restants par stockage et type" :rows="remainingRows" :columns="REMAINING_COLUMNS" :row-key="row => row.key"><template #cell-bytes="{row}">{{ gb(row.bytes) }}</template></UiDataTable></article>
      <article class="storage-card wide">
        <h2>À traiter · {{ issues.length }}</h2>
        <p>Une copie ne libère de place qu’après validation et suppression de l’original. Les attentes et erreurs ne bloquent pas les autres titres.</p>
        <p v-if="!issues.length">Aucun titre à traiter.</p>
        <details v-for="item in issues" :key="item.id"><summary>{{ item.title }} · {{ status(item.status) }}</summary><p>{{ item.reason }}</p><p>Original : {{ item.snapshot.source_arr }}</p><p>Destination : {{ item.snapshot.destination_arr }}</p></details>
      </article>
      <article class="storage-card wide"><h2>Historique récent</h2><p v-if="!recentRows.length">Aucun lot terminé ou interrompu.</p><UiDataTable v-else label="Historique récent des lots" :rows="recentRows" :columns="HISTORY_COLUMNS" :row-key="row => row.id"><template #cell-volume="{row}">{{ gb(row.volume) }}</template></UiDataTable><UiButton @click="tab='history'">Voir tout l’historique</UiButton></article>
    </section>

    <section v-if="tab === 'prepare'" class="storage-card">
      <h2>Préparer un déplacement</h2><p>Choisissez le stockage à désengorger et une destination. L’aperçu propose les titres les plus volumineux ; vous gardez la décision finale.</p>
      <form @submit.prevent="preview">
        <div class="form-grid">
          <label>Source<select v-model.number="form.source_id" required><option :value="0" disabled>Choisir</option><option v-for="l in locations" :key="l.id" :value="l.id">{{ l.name }}</option></select></label>
          <label>Destination<select v-model.number="form.destination_id" required><option :value="0" disabled>Choisir</option><option v-for="l in locations.filter(x => x.id !== form.source_id)" :key="l.id" :value="l.id">{{ l.name }}</option></select></label>
          <label>Objectif<select v-model="form.mode"><option value="release_space">Libérer un volume</option><option value="minimum_free">Atteindre un espace libre minimum</option><option value="selection">Choisir des titres</option></select></label>
          <label>Objectif en Go<input v-model.number="form.goal_gb" type="number" min="1" required /></label>
          <label>Type<select v-model="form.media_type"><option value="all">Films et séries</option><option value="movie">Films</option><option value="series">Séries</option></select></label>
          <label>Maximum de titres<input v-model.number="form.max_titles" type="number" min="1" max="250" required /></label>
          <label>Vérification<select v-model="form.verification"><option value="standard">Standard · rsync</option><option value="renforce">Renforcée · SHA-256</option></select></label>
          <label class="check"><input v-model="form.auto_resume" type="checkbox" /> Reprendre après un redémarrage</label>
        </div><UiButton type="submit" variant="primary" :loading="busy">Calculer l’aperçu</UiButton>
      </form>
      <p class="hint">Les stockages doivent être montés dans le conteneur de transfert et leurs dossiers enregistrés dans Sonarr/Radarr et Plex. Les règles automatiques ne sont pas activées dans cette première version.</p>
    </section>

    <section v-if="tab === 'transfers' || tab === 'history'" class="job-list">
      <p v-if="!visibleJobs.length">Aucune tâche dans cette section.</p>
      <article v-for="job in visibleJobs" :key="job.id" class="storage-card">
        <header><h2>{{ locationName(job.source_id) }} → {{ locationName(job.destination_id) }}</h2><strong>{{ status(job.status) }}</strong></header>
        <p>{{ gb(job.released_bytes) }} libérés · {{ gb(job.planned_bytes) }} prévus · créé le {{ date(job.created_at) }}</p><p>{{ job.items.filter((i:any)=>i.media_type==='movie').length }} film(s) · {{ job.items.filter((i:any)=>i.media_type==='series').length }} série(s) · {{ job.items.filter((i:any)=>['blocked','deferred','plex_pending'].includes(i.status)).length }} titre(s) à traiter</p><p>Début : {{ jobStart(job) ? date(jobStart(job)) : 'Non enregistré' }} · Fin : {{ jobEnd(job) ? date(jobEnd(job)) : 'Non terminé' }} · Durée écoulée : {{ elapsed(job) }}</p>
        <p v-if="job.desired_state !== 'run'">{{ job.desired_state === 'pause' ? 'Pause' : 'Arrêt' }} demandé : les fichiers partiels restent conservés.</p>
        <div v-if="job.status !== 'completed'" class="actions"><UiButton :disabled="busy || job.desired_state === 'pause'" @click="command(job.id, 'pause')">Pause</UiButton><UiButton :disabled="busy || job.status === 'running'" @click="command(job.id, 'resume')">Reprendre / revérifier</UiButton><UiButton :disabled="busy || job.desired_state === 'stop'" @click="command(job.id, 'stop')">Arrêter et conserver</UiButton></div>
        <div v-for="item in job.items" :key="item.id" class="transfer-item">
          <div class="item-head"><strong>{{ item.title }}</strong><span>{{ status(item.status) }} · {{ gb(item.size_bytes) }}</span></div>
          <template v-if="item.status === 'copying'"><p>{{ item.progress.file }} · {{ gb(item.progress.bytes) }} copiés sur ce fichier</p></template>
          <p v-if="item.reason" class="warning">{{ item.reason }}</p>
          <details><summary>Chemins et activité</summary><p>Original : {{ item.snapshot.source_arr }}</p><p>Destination : {{ item.snapshot.destination_arr }}</p><small>{{ date(item.updated_at) }}</small></details>
        </div>
      </article>
    </section>

    <section v-if="tab === 'settings'" class="storage-card">
      <h2>Stockages et correspondances</h2><p>Une correspondance associe deux chemins qui doivent désigner les mêmes fichiers : celui vu par Sonarr/Radarr et celui vu par Plex. Les noms peuvent être différents selon leurs montages.</p>
      <div class="mapping-help"><strong>Comment savoir si c’est bon ?</strong><ol><li>Choisissez une instance, puis son dossier racine Arr et le dossier Plex supposé correspondant.</li><li>Cliquez sur « Vérifier cette correspondance ». Le contrôle compare les fichiers et les identifiants TMDB/TVDB sur cinq titres maximum.</li><li>En cas de concordance, enregistrez le stockage. Le montage du moteur sera contrôlé séparément avant tout déplacement.</li></ol><p>« Racines détectées » signifie uniquement que les chemins sont déclarés. Cela ne confirme pas leur correspondance.</p></div>
      <div v-for="l in locations" :key="l.id" class="history-row"><strong>{{ l.name }}</strong><span>{{ l.mount_path }}</span><UiButton @click="editLocation(l)">Modifier</UiButton></div>
      <h3>Racines détectées par les API</h3>
      <p>Les chemins peuvent différer entre conteneurs. La détection confirme leur déclaration ; la comparaison du contenu contrôle les fichiers et les identifiants des titres.</p>

      <UiDataTable class="root-table" label="Correspondance des racines Arr et Plex" :rows="rootRows" :columns="ROOT_COLUMNS" :row-key="row => row.key">
        <template #cell-instance="{row}"><strong>{{ row.instance }}</strong><small>{{ row.kind === 'radarr' ? 'Films' : 'Séries' }}</small></template>
        <template #cell-arr_root="{row}"><code>{{ row.arr_root || 'Aucune racine détectée' }}</code></template>
        <template #cell-plex_root="{row}"><label><span class="sr-only">Dossier Plex correspondant à {{ row.instance }} {{ row.arr_root }}</span><select v-model="rootPairs[row.key]" :disabled="Boolean(row.error)"><option value="">Choisir le dossier Plex</option><option v-for="plex in row.plex_roots" :key="plex.section_id + plex.path" :value="JSON.stringify([plex.section_id,plex.path])">{{ plex.library }} · {{ plex.path }}</option></select></label></template>
        <template #cell-check="{row}"><p :class="draftComparisons[draftKey(rootMapping(row))]?.status === 'sample_matched' ? 'healthy' : 'warning'">{{ row.error || (!rootPairs[row.key] ? 'Correspondance à choisir' : comparisonLabel(draftComparisons[draftKey(rootMapping(row))])) }}</p><UiButton :loading="checking === draftKey(rootMapping(row))" :disabled="checking !== '' || !rootPairs[row.key] || Boolean(row.error)" @click="checkDraft(rootMapping(row))">Vérifier</UiButton><UiButton :disabled="busy || !rootPairs[row.key] || Boolean(row.error)" @click="saveRoot(row)">Enregistrer</UiButton><details v-if="draftComparisons[draftKey(rootMapping(row))]?.items?.length"><summary>Résultat détaillé</summary><small>{{ date(draftComparisons[draftKey(rootMapping(row))].checked_at) }} · contrôle en lecture seule</small><p v-for="item in draftComparisons[draftKey(rootMapping(row))].items" :key="item.title">{{ item.title }} : {{ item.reason || `${item.files} fichier(s) et identité concordants` }}</p><p v-if="draftComparisons[draftKey(rootMapping(row))].pending_titles">{{ draftComparisons[draftKey(rootMapping(row))].pending_titles }} titre(s) sans fichier, écartés.</p></details></template>
      </UiDataTable>
      <h3>Comparaison des correspondances enregistrées</h3>
      <p v-if="!locations.length">Enregistrez un stockage et ses correspondances pour comparer leur contenu.</p>
      <UiDataTable v-if="mappingRows.length" label="Correspondances enregistrées par stockage" :rows="mappingRows" :columns="MAPPING_COLUMNS" :row-key="row => row.key">
        <template #cell-location="{row}"><strong>{{ row.location }}</strong><small>{{ row.instance }}</small></template>
        <template #cell-arr_root="{row}"><code>{{ row.mapping.arr_root }}</code></template>
        <template #cell-plex_root="{row}"><code>{{ row.mapping.plex_root }}</code><small>Bibliothèque {{ row.mapping.plex_section_id }}</small></template>
        <template #cell-check="{row}"><p>{{ comparisonLabel(comparisons[row.key]) }}</p><small v-if="comparisons[row.key]?.checked_at">{{ date(comparisons[row.key].checked_at) }}</small><UiButton :loading="checking === row.key" :disabled="checking !== ''" @click="checkMapping(row.location_id,row.index)">Comparer le contenu</UiButton><details v-if="comparisons[row.key]?.items?.length"><summary>Détail des titres contrôlés</summary><p v-for="item in comparisons[row.key].items" :key="item.title">{{ item.title }} : {{ item.reason || `${item.files} fichier(s) et identité concordants` }}</p><small>{{ comparisons[row.key].note }}</small></details></template>
      </UiDataTable>
      <UiButton @click="resetLocation(); locationDialog = true">Configurer un stockage pour les déplacements</UiButton>
      <ModalShell :open="locationDialog" title="Enregistrer le stockage et sa correspondance" :busy="busy" @close="locationDialog = false">
      <p>La correspondance choisie est préremplie. Indiquez le montage vu par le moteur pour enregistrer le stockage ; aucun transfert ne sera lancé.</p><UiFeedback v-if="error" type="error" :message="error" />
      <form @submit.prevent="saveLocation">
        <h3>{{ editId ? 'Modifier le stockage' : 'Ajouter un stockage' }}</h3>
        <div class="form-grid"><label>Nom<input v-model="locationForm.name" required maxlength="100" /></label><label>Montage du moteur<input v-model="locationForm.mount_path" placeholder="/storage/data1" required /></label><label>Réserve en Go<input v-model.number="locationForm.reserve_gb" type="number" min="0" required /></label><label class="check"><input v-model="locationForm.enabled" type="checkbox" /> Actif</label></div>
        <fieldset v-for="(mapping, index) in locationForm.mappings" :key="index"><legend>Correspondance {{ index + 1 }}</legend><div class="form-grid"><label>Instance<select v-model.number="mapping.arr_instance_id" required @change="resetMappingRoots(mapping)"><option v-for="i in instances" :key="i.id" :value="i.id">{{ i.name }} · {{ i.arr_type }}</option></select></label><label>Sous-dossier du montage<input v-model="mapping.subdirectory" placeholder="FILMS ou SERIES" /></label><label>Dossier racine déclaré dans Arr<select v-model="mapping.arr_root" required><option value="" disabled>Choisir un dossier vérifié</option><option v-for="root in rootsFor(mapping).arr_roots" :key="root" :value="root">{{ root }}</option></select></label><label>Dossier déclaré dans Plex<select :value="plexChoice(mapping)" required @change="selectPlexRoot(mapping, ($event.target as HTMLSelectElement).value)"><option value="" disabled>Choisir la bibliothèque et son dossier</option><option v-for="root in rootsFor(mapping).plex_roots" :key="JSON.stringify([root.section_id, root.path])" :value="JSON.stringify([root.section_id, root.path])">{{ root.library }} · {{ root.path }}</option></select></label><p v-if="rootsFor(mapping).error" class="warning">{{ rootsFor(mapping).error }}</p></div><div class="mapping-check"><p v-if="mapping.arr_root && mapping.plex_root"><strong>À comparer :</strong> {{ mapping.arr_root }} ↔ {{ mapping.plex_root }}</p><UiButton :loading="checking === draftKey(mapping)" :disabled="checking !== '' || !mapping.arr_root || !mapping.plex_root" @click="checkDraft(mapping)">Vérifier cette correspondance</UiButton><div v-if="draftComparisons[draftKey(mapping)]" aria-live="polite"><p :class="draftComparisons[draftKey(mapping)].status === 'sample_matched' ? 'healthy' : 'warning'">{{ comparisonLabel(draftComparisons[draftKey(mapping)]) }}</p><small v-if="draftComparisons[draftKey(mapping)].checked_at">Contrôlé le {{ date(draftComparisons[draftKey(mapping)].checked_at) }} · aucun fichier déplacé</small><details v-if="draftComparisons[draftKey(mapping)].items?.length"><summary>Voir les titres et fichiers contrôlés</summary><p v-for="item in draftComparisons[draftKey(mapping)].items" :key="item.title">{{ item.title }} : {{ item.reason || `${item.files} fichier(s) et identité concordants` }}</p></details><p>Le contrôle porte sur cet échantillon ; tous les titres seront revérifiés avant leur déplacement. Il ne confirme pas le montage du moteur.</p></div></div><UiButton v-if="locationForm.mappings.length > 1" @click="locationForm.mappings.splice(index, 1)">Retirer cette correspondance</UiButton></fieldset>
        <div class="actions"><UiButton @click="locationForm.mappings.push(newMapping())">Ajouter une correspondance</UiButton><UiButton type="submit" variant="primary" :loading="busy">Enregistrer</UiButton><UiButton v-if="editId" @click="resetLocation(); locationDialog = false">Annuler</UiButton></div>
      </form>
      </ModalShell>
    </section>

    <ModalShell v-if="plan" :open="Boolean(plan)" title="Aperçu du déplacement" :busy="busy" @close="plan = null">
      <p>{{ locationName(form.source_id) }} → {{ locationName(form.destination_id) }} · {{ gb(selectedBytes) }} estimés pour {{ selected.length }} titre(s)</p>
      <p v-if="!plan.goal_covered" class="warning">L’objectif demandé ne peut pas être entièrement couvert par ce lot.</p><p>{{ plan.note }}</p>
      <label v-for="item in plan.items" :key="item.key" class="preview-choice"><input v-model="selected" :value="item.key" type="checkbox" /><span><strong>{{ item.title }}</strong> · {{ gb(item.size_bytes) }}<small>{{ item.explanation }}</small></span></label>
      <details v-if="plan.excluded.length"><summary>{{ plan.excluded.length }} titre(s) écartés</summary><p v-for="item in plan.excluded" :key="item.key">{{ item.title }} : {{ item.explanation }}</p></details>
      <template #footer><UiButton :disabled="busy" @click="plan = null">Annuler</UiButton><UiButton variant="primary" :loading="busy" :disabled="!selected.length" @click="launch">Lancer la sélection</UiButton></template>
    </ModalShell>
  </AppPage>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue';
import { api } from '@/api';
import { useRealtime } from '@/events';
import UiButton from '@/components/ui/UiButton.vue';
import UiFeedback from '@/components/ui/UiFeedback.vue';
import UiDataTable, { type UiColumn } from '@/components/ui/UiDataTable.vue';
import ModalShell from '@/components/ui/ModalShell.vue';
const tabs=[{key:'overview',label:'Vue d’ensemble'},{key:'prepare',label:'Préparer'},{key:'transfers',label:'Transferts'},{key:'history',label:'Historique'},{key:'settings',label:'Stockages'}];
const tab=ref('overview'),locations=ref<any[]>([]),jobs=ref<any[]>([]),instances=ref<any[]>([]),discoveredRoots=ref<any[]>([]),loading=ref(false),busy=ref(false),error=ref(''),plan=ref<any>(null),selected=ref<string[]>([]),editId=ref<number|null>(null);
const rootsLoading=ref(false),checking=ref(''),comparisons=ref<Record<string,any>>({}),draftComparisons=ref<Record<string,any>>({});
const rootPairs=ref<Record<string,string>>({});
const locationDialog=ref(false);
function saveRoot(row:any){const mapping=rootMapping(row);const existing=locations.value.find(l=>l.mappings.some((m:any)=>m.arr_instance_id===row.arr_instance_id && m.arr_root===row.arr_root));if(existing){editLocation(existing);const index=locationForm.value.mappings.findIndex((m:any)=>m.arr_instance_id===row.arr_instance_id && m.arr_root===row.arr_root);locationForm.value.mappings[index]={...locationForm.value.mappings[index],...mapping,subdirectory:locationForm.value.mappings[index].subdirectory};}else{resetLocation();locationForm.value.name=`${row.instance} · ${row.arr_root}`;locationForm.value.mount_path="";locationForm.value.mappings=[mapping];}error.value="";locationDialog.value=true;}
const ROOT_COLUMNS:UiColumn[]=[{key:'instance',label:'Instance',sortable:true,card:'title'},{key:'arr_root',label:'Racine Arr',sortable:true},{key:'plex_root',label:'Racine Plex à associer'},{key:'check',label:'Contrôle'}];
const MAPPING_COLUMNS:UiColumn[]=[{key:'location',label:'Stockage / instance',sortable:true,card:'title'},{key:'arr_root',label:'Racine Arr'},{key:'plex_root',label:'Racine Plex'},{key:'check',label:'Contrôle du contenu'}];
const rootRows=computed(()=>discoveredRoots.value.flatMap(root=>(root.arr_roots.length?root.arr_roots:['']).map((path:string)=>({key:`${root.arr_instance_id}:${path}`,arr_instance_id:root.arr_instance_id,instance:root.name,kind:root.arr_type,arr_root:path,plex_roots:root.plex_roots,error:root.error}))));
const mappingRows=computed(()=>locations.value.flatMap(location=>location.mappings.map((mapping:any,index:number)=>({key:comparisonKey(location.id,index),location:location.name,location_id:location.id,index,instance:instances.value.find(i=>i.id===mapping.arr_instance_id)?.name||mapping.arr_instance_id,mapping}))));
function rootMapping(row:any){const choice=rootPairs.value[row.key];const [section,path]=choice?JSON.parse(choice):['',''];return {arr_instance_id:row.arr_instance_id,arr_root:row.arr_root,plex_root:path,plex_section_id:section,subdirectory:''};}
const draftKey=(mapping:any)=>JSON.stringify([mapping.arr_instance_id,mapping.arr_root,mapping.plex_section_id,mapping.plex_root]);
async function checkDraft(mapping:any){const key=draftKey(mapping);checking.value=key;try{draftComparisons.value[key]=await api('/api/storage/roots/check',{method:'POST',body:JSON.stringify(mapping)});}catch(e:any){draftComparisons.value[key]={error:e.message};}finally{checking.value='';}}
const comparisonKey=(id:number,index:number|string)=>`${id}:${index}`;
const comparisonLabel=(result:any)=>!result?'Contenu non contrôlé':result.error?result.error:result.status==='empty'?'Aucun fichier présent permettant la comparaison':result.status==='incomplete'?'Contrôle incomplet : certains fichiers annoncés par Arr sont indisponibles':result.status==='mismatch'?'Écart détecté — correspondance à corriger':`Correspondance confirmée sur ${result.checked_titles} / ${result.total_titles} titre(s), contrôle limité à l’échantillon`;
let rootsCheckedAt=0;
async function refreshRoots(silent=false){if(rootsLoading.value)return;rootsLoading.value=true;try{const next=await api<any[]>('/api/storage/roots');if(JSON.stringify(next)!==JSON.stringify(discoveredRoots.value)){discoveredRoots.value=next;const pairs:Record<string,string>={};for(const root of next){for(const path of root.arr_roots){const key=`${root.arr_instance_id}:${path}`;const saved=locations.value.flatMap(l=>l.mappings).find(m=>m.arr_instance_id===root.arr_instance_id && m.arr_root===path);const choice=rootPairs.value[key] ?? (saved?JSON.stringify([saved.plex_section_id,saved.plex_root]):'');pairs[key]=root.plex_roots.some((p:any)=>JSON.stringify([p.section_id,p.path])===choice)?choice:'';}}rootPairs.value=pairs;instances.value=next.map(r=>({id:r.arr_instance_id,name:r.name,arr_type:r.arr_type}));for(const mapping of locationForm.value.mappings){if(!mapping.arr_instance_id)mapping.arr_instance_id=instances.value[0]?.id||0;}}rootsCheckedAt=Date.now();}catch(e:any){if(!silent)error.value=e.message;}finally{rootsLoading.value=false;}}

async function checkMapping(id:number,index:number|string){const key=comparisonKey(id,index);checking.value=key;try{comparisons.value[key]=await api(`/api/storage/locations/${id}/mappings/${index}/check`,{method:'POST'});}catch(e:any){comparisons.value[key]={error:e.message};}finally{checking.value='';}}
const form=ref({source_id:0,destination_id:0,mode:'release_space',goal_gb:500,media_type:'all',max_titles:20,verification:'standard',auto_resume:true});
const newMapping=()=>({arr_instance_id:instances.value[0]?.id||0,arr_root:'',plex_root:'',plex_section_id:'',subdirectory:''});
const locationForm=ref({name:'',mount_path:'/storage/',reserve_gb:100,enabled:true,mappings:[newMapping()]});
const rootsFor=(mapping:any)=>discoveredRoots.value.find(r=>r.arr_instance_id===mapping.arr_instance_id)||{arr_roots:[],plex_roots:[]};
function resetMappingRoots(mapping:any){mapping.arr_root='';mapping.plex_root='';mapping.plex_section_id='';}
const plexChoice=(mapping:any)=>mapping.plex_root?JSON.stringify([mapping.plex_section_id,mapping.plex_root]):'';
function selectPlexRoot(mapping:any,value:string){const [section,path]=JSON.parse(value);mapping.plex_section_id=section;mapping.plex_root=path;}
const allItems=computed(()=>jobs.value.flatMap(j=>j.items.map((item:any)=>({...item,source_id:j.source_id}))));
const remainingItems=computed(()=>allItems.value.filter(i=>i.status!=='completed'));
const completedItems=computed(()=>allItems.value.filter(i=>i.status==='completed'));
const remainingBytes=computed(()=>remainingItems.value.reduce((sum,item)=>sum+item.size_bytes,0));
const releasedBytes=computed(()=>completedItems.value.reduce((sum,item)=>sum+item.size_bytes,0));
const activeJobs=computed(()=>jobs.value.filter(j=>['queued','running'].includes(j.status)));
const pausedJobs=computed(()=>jobs.value.filter(j=>['paused','stopped'].includes(j.status)));
const remainingFor=(id:number)=>remainingItems.value.filter(i=>i.source_id===id);
const REMAINING_COLUMNS:UiColumn[]=[{key:'location',label:'Stockage source',card:'title'},{key:'type',label:'Type'},{key:'count',label:'Titres restants'},{key:'bytes',label:'Volume restant'}];
const remainingRows=computed(()=>locations.value.flatMap(l=>['movie','series'].map(type=>{const items=remainingFor(l.id).filter(i=>i.media_type===type);return {key:`${l.id}:${type}`,location:l.name,type:type==='movie'?'Films':'Séries',count:items.length,bytes:items.reduce((sum,i)=>sum+i.size_bytes,0)};})).filter(r=>r.count));
const usedPercent=(l:any)=>l.total_bytes>0?Math.min(100,Math.max(0,Math.round((l.total_bytes-l.free_bytes)/l.total_bytes*100))):0;
const reservePercent=(l:any)=>l.total_bytes>0?Math.min(100-usedPercent(l),l.reserve_bytes/l.total_bytes*100):0;
function projectedFree(l:any){if(l.free_bytes==null)return null;const outgoing=remainingFor(l.id).reduce((n,i)=>n+i.size_bytes,0);const incoming=jobs.value.filter(j=>j.destination_id===l.id).flatMap(j=>j.items).filter(i=>i.status!=='completed').reduce((n,i)=>n+Math.max(0,i.size_bytes-(i.progress?.copied_bytes||0)),0);return Math.max(0,l.free_bytes+outgoing-incoming);}
const activeItem=(job:any)=>job.items.find((i:any)=>['prepared','copying','verifying','switching','plex_pending','cleaning'].includes(i.status));
const copyPercent=(i:any)=>i.size_bytes>0?Math.min(100,Math.max(0,Math.round((i.progress?.copied_bytes||0)/i.size_bytes*100))):0;
const duration=(seconds:number)=>seconds<60?`${Math.ceil(seconds)} s`:seconds<3600?`${Math.ceil(seconds/60)} min`:`${Math.floor(seconds/3600)} h ${Math.ceil(seconds%3600/60)} min`;
function measuredRate(i:any){const p=i?.progress;return i?.status==='copying' && p?.bytes_per_second>0 && Date.now()/1000-p.updated_at<15?p.bytes_per_second:null;}
const rateLabel=(i:any)=>measuredRate(i)?`${(measuredRate(i)/1e6).toLocaleString('fr-FR',{maximumFractionDigits:1})} Mo/s`:'Débit en attente de mesure';
function copyEta(job:any){const item=activeItem(job),rate=measuredRate(item);if(!rate || job.desired_state!=='run')return 'Estimation indisponible';const bytes=job.items.filter((i:any)=>i.status!=='completed').reduce((n:number,i:any)=>n+Math.max(0,i.size_bytes-(i.progress?.copied_bytes||0)),0);return `≈ ${duration(bytes/rate)}`;}
const HISTORY_COLUMNS:UiColumn[]=[{key:'route',label:'Trajet',card:'title'},{key:'state',label:'État'},{key:'titles',label:'Films / séries'},{key:'volume',label:'Volume libéré'},{key:'dates',label:'Début / fin'},{key:'duration',label:'Durée écoulée'},{key:'deferred',label:'À traiter'}];
function jobStart(j:any){return j.items.map((i:any)=>i.progress?.started_at).filter(Boolean).sort()[0];}
function jobEnd(j:any){return j.status==='completed'?j.items.map((i:any)=>i.progress?.finished_at).filter(Boolean).sort().at(-1):null;}
function elapsed(j:any){const start=jobStart(j),end=jobEnd(j);return start && end?duration(Math.max(0,(new Date(end).getTime()-new Date(start).getTime())/1000)):'Indisponible';}
const recentRows=computed(()=>jobs.value.filter(j=>['completed','blocked','stopped','paused'].includes(j.status)).slice(0,5).map(j=>({id:j.id,route:`${locationName(j.source_id)} → ${locationName(j.destination_id)}`,state:status(j.status),titles:`${j.items.filter((i:any)=>i.media_type==='movie').length} film(s) / ${j.items.filter((i:any)=>i.media_type==='series').length} série(s)`,volume:j.released_bytes,dates:`${jobStart(j)?date(jobStart(j)):'Début non enregistré'} / ${jobEnd(j)?date(jobEnd(j)):'Non terminé'}`,duration:elapsed(j),deferred:j.items.filter((i:any)=>['blocked','deferred','plex_pending'].includes(i.status)).length})));
const issues=computed(()=>jobs.value.flatMap(j=>j.items).filter(i=>['blocked','deferred','plex_pending'].includes(i.status)));
const visibleJobs=computed(()=>jobs.value.filter(j=>tab.value==='history'?['completed','blocked','stopped','paused'].includes(j.status):j.status!=='completed'));
const selectedBytes=computed(()=>plan.value?.items.filter((i:any)=>selected.value.includes(i.key)).reduce((a:number,i:any)=>a+i.size_bytes,0)||0);
const gb=(n:any)=>n==null?'—':`${(Number(n)/1e9).toLocaleString('fr-FR',{maximumFractionDigits:1})} Go`;
const date=(n:any)=>n?new Date(n.endsWith('Z')?n:n+'Z').toLocaleString('fr-FR'):'Non contrôlé';
const locationName=(id:number)=>locations.value.find(l=>l.id===id)?.name||`Stockage ${id}`;
const labels:Record<string,string>={queued:'En attente',running:'En cours',pending:'En attente',prepared:'Préparé',copying:'Copie',verifying:'Vérification',switching:'Bascule Arr',plex_pending:'Confirmation Plex',cleaning:'Nettoyage',completed:'Terminé',blocked:'À traiter',deferred:'Reporté',paused:'En pause',stopped:'Arrêté'};
const status=(value:string)=>labels[value]||value;
async function load(silent=false){if(loading.value)return;loading.value=true;try{const [nextLocations,nextJobs]=await Promise.all([api<any[]>('/api/storage/locations'),api<any[]>('/api/storage/transfers')]);if(JSON.stringify(locations.value.map(l=>[l.id,l.mappings]))!==JSON.stringify(nextLocations.map(l=>[l.id,l.mappings])))comparisons.value={};if(JSON.stringify(locations.value)!==JSON.stringify(nextLocations))locations.value=nextLocations;if(JSON.stringify(jobs.value)!==JSON.stringify(nextJobs))jobs.value=nextJobs;}catch(e:any){if(!silent)error.value=e.message;}finally{loading.value=false;}}
async function act(fn:()=>Promise<void>){busy.value=true;error.value='';try{await fn();}catch(e:any){error.value=e.message;}finally{busy.value=false;}}
const preview=()=>act(async()=>{plan.value=await api('/api/storage/preview',{method:'POST',body:JSON.stringify(form.value)});selected.value=plan.value.items.map((i:any)=>i.key);});
const launch=()=>act(async()=>{await api('/api/storage/transfers',{method:'POST',body:JSON.stringify({...form.value,selection:selected.value})});plan.value=null;tab.value='transfers';await load();});
const command=(id:number,action:string)=>act(async()=>{await api(`/api/storage/transfers/${id}/command`,{method:'POST',body:JSON.stringify({action})});await load();});
function resetLocation(){editId.value=null;locationForm.value={name:'',mount_path:'/storage/',reserve_gb:100,enabled:true,mappings:[newMapping()]};}
function editLocation(l:any){locationDialog.value=true;editId.value=l.id;locationForm.value={name:l.name,mount_path:l.mount_path,reserve_gb:l.reserve_bytes/1e9,enabled:l.enabled,mappings:structuredClone(l.mappings)};}
const saveLocation=()=>act(async()=>{await api('/api/storage/locations'+(editId.value?`/${editId.value}`:''),{method:editId.value?'PUT':'POST',body:JSON.stringify(locationForm.value)});comparisons.value={};resetLocation();locationDialog.value=false;await load();});
let timer:ReturnType<typeof setInterval>|undefined;
function backgroundRefresh(){if(document.hidden)return;void load(true);if(Date.now()-rootsCheckedAt>=60000)void refreshRoots(true);}
onMounted(async()=>{await load();await refreshRoots();timer=setInterval(backgroundRefresh,5000);document.addEventListener('visibilitychange',backgroundRefresh);});
onUnmounted(()=>{if(timer)clearInterval(timer);document.removeEventListener('visibilitychange',backgroundRefresh);});
useRealtime(['storage.updated'],()=>void load(true),{debounceMs:600});
</script>

<style scoped lang="scss">
@use "@/styles/foundations/breakpoints" as bp;
.mapping-help,.mapping-check{padding:16px;margin:16px 0;border-radius:12px;background:var(--surface-2);line-height:1.6}.mapping-help li{margin:8px 0}.ui-data-table{margin:18px 0}.ui-data-table code{white-space:normal;overflow-wrap:anywhere}.ui-data-table select{width:100%;max-width:100%}.ui-data-table small{display:block}.ui-data-table p{margin:0 0 10px}.ui-data-table :deep(td){white-space:normal;overflow-wrap:anywhere}.ui-data-table label{min-width:0}@include bp.until(shell-medium){.ui-data-table :deep(td){display:grid;grid-template-columns:minmax(0,1fr);text-align:left}.ui-data-table :deep(td::before){white-space:normal;overflow-wrap:anywhere}}@include bp.from(shell-medium){.root-table :deep(table){table-layout:fixed}.root-table :deep(th:nth-child(1)){width:14%}.root-table :deep(th:nth-child(2)){width:21%}.root-table :deep(th:nth-child(3)){width:33%}.root-table :deep(th:nth-child(4)){width:32%}}

.capacity-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,280px),1fr));gap:20px}.capacity-card{border:1px solid var(--border);border-radius:12px;padding:18px}.capacity-track{height:12px;display:flex;border-radius:8px;overflow:hidden;background:var(--surface-2);margin-top:16px}.capacity-used{background:var(--accent)}.capacity-reserve{background:var(--green-text)}.active-transfer{padding:16px 0}.active-transfer progress{width:100%;height:16px;accent-color:var(--accent)}
.summary-card{display:flex;flex-direction:column;min-width:0}.summary-card h2{margin-top:0}.summary-card small{display:block;margin-bottom:20px}.card-footer{margin-top:auto;padding-top:16px}.card-footer :deep(button){width:100%}.storage-grid>.storage-card{margin-bottom:0}
.storage-tabs,.actions{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:20px}.storage-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.storage-card{padding:24px;border:1px solid var(--border);border-radius:16px;background:var(--surface);margin-bottom:20px;overflow-wrap:anywhere}.wide{grid-column:1/-1}.metric{font-size:28px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;margin:20px 0}label{display:flex;flex-direction:column;gap:8px}input,select{min-height:44px;padding:10px;border-radius:8px;border:1px solid var(--border);background:var(--surface-2);color:inherit;font:inherit;min-width:0}.check{flex-direction:row;align-items:center}.check input,.preview-choice input{min-height:22px}.hint,small{opacity:.75;line-height:1.6}.history-row,.item-head,header{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}.history-row,.transfer-item{padding:16px 0;border-bottom:1px solid var(--border)}.warning{color:var(--accent)}.healthy{color:var(--green-text)}fieldset{border:1px solid var(--border);border-radius:12px;padding:16px;margin-bottom:16px}.preview-choice{display:flex;flex-direction:row;align-items:flex-start;padding:12px 0;gap:12px}.preview-choice small{display:block}details{padding:10px 0}summary{cursor:pointer;min-height:44px;align-content:center}.job-list{display:grid;gap:16px}h2{font-size:20px}h3{margin-top:24px}@include bp.until(shell-medium){.storage-grid,.form-grid{grid-template-columns:1fr}.storage-card{padding:18px}.storage-tabs{gap:6px}.metric{font-size:25px}}
</style>
